[project]
name = "perdiver"
version = "0.0.1"
dependencies = [
    "numpy", "matplotlib",
]
[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["."]  # ["."] by default
include = ["perdiver*"]  # ["*"] by default
namespaces = false  # true by default
